// <auto-generated />
namespace BrowseDotNet.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_lasttimeopened_to_solution : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_lasttimeopened_to_solution));
        
        string IMigrationMetadata.Id
        {
            get { return "201504181353103_add_lasttimeopened_to_solution"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
