// <auto-generated />
namespace BrowseDotNet.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class programming_languages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(programming_languages));
        
        string IMigrationMetadata.Id
        {
            get { return "201504180658156_programming_languages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
