// <auto-generated />
namespace BrowseDotNet.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_code_tosnippet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_code_tosnippet));
        
        string IMigrationMetadata.Id
        {
            get { return "201504180716301_add_code_tosnippet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
